spring:
  datasource:
    url: jdbc:h2:mem:catalog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql.init.mode: always

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace